// This file is automatically generated. Do not edit it directly.
// Modificado para usar a instância já existente do cliente Supabase
import { supabase } from '@/lib/supabase';

// Re-export para manter a compatibilidade
export { supabase };